version: '3.8'

services:
  viya4oc:
    container_name: viya4oc
    build: .
    ports:
      - "7891:80"
    volumes:
      - ./src:/var/www/html
      - ../cmd:/var/www/cmd:ro
      - ../cmd_cli:/var/www/cmd_cli:ro
      - ../config.env:/var/www/config.env:ro
